# Generated by Django 4.2.1 on 2023-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='refresh',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
