# Generated by Django 4.2.1 on 2023-05-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='refresh',
        ),
        migrations.AddField(
            model_name='customuser',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'visitor'), (1, 'Admin')], default=0),
        ),
    ]
