# Generated by Django 4.2.1 on 2023-05-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_refresh_customuser_refresh_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='refresh_token',
            new_name='refresh',
        ),
    ]
